### ISSUE TITLE
[Content] Lightning Vessel Issues

### ISSUE THREAD

**Issue by Drag0nF** [trioderegion/steinhardts-support-desk#1]
It would be better to just have the 'Fulgurant Strike' action of the barbarian set up to target a 7.5 foot radius rather than a creature, and change it to be a 'Saving Throw' rather than a 'melee weapon attack' in the Action Type field.

Additionally, the scale.vessel.galvanised scaling doesn't work, showing up as 0 in the damage calculations. 

Furthermore, it may be worth adding a passive effect to the Galvanised heart item that while active will add Resistance to Lightning damage (though an effect that uses 'system.traits.dr.lightning' I believe)

**Comment by trioderegion** [comment]
1) ✅, 7.5ft is a decent default. I will also add a usage note to the item.

2) ❓, Can you point to where this scale value is being used? I may have already fixed it on my side, but I only see references to `scale.vessel.galvanic` currently.

3) ❌ , keeping with best practices, permanent changes to your character should not be done via Active Effects.

**Comment by Drag0nF** [comment]
i. cool!

ii. May have misspelled it, but if you say it's been fixed then it probably has- it's original use was in the features, such as Fulgurant strike it would be 'scale.vessel.galvanic' * con modifier. Issue is that before, it wouldn't work- the amount would simply output to 0- it would seemingly equal 0, as when checking the output, the con modifier is  properly showing up, but the 'scale.vessel.galvanic' used to calculate as 0- but, this is likely already fixed as I posted about it before in the vtt feedback channel and you replied

iii. fair enough! that's just what I do for my custom stuff, but if that is not the best practices, then fair enough!

**Comment by trioderegion** [comment]
I will double check that the scale modifier is being correctly used. Thanks for explaining further 👍
