### ISSUE TITLE
[Content] Vigilant Nature Missing on Foundry VTT

### ISSUE THREAD

**Issue by UmbraZeal** [trioderegion/steinhardts-support-desk#10]
**Describe the issue**
The feature Vigilant Nature for Cursed-Bloods are missing both in the race description and as a feature.
**Observed locations**
Foundry VTT Module

**Expected corrections**
Adding Vigilant Nature to both the Cursed-Blood description and adding it as a feature.

**Comment by trioderegion** [comment]
Thank you for the report 👍 . The missing text has been added to the `Cursed-Blood` race feature. As it is a passive trait with no real "action" to perform (as far as foundry is concerned), I do not believe it needs a separate item.

If I have missed some detail or a particular workflow would be greatly aided by its addition, please do reply and re-open the issue if needed.
