### ISSUE TITLE
[Content] Parasitic Geist Missing Icon For Devour Life. (Foundry VTT)

### ISSUE THREAD

**Issue by UmbraZeal** [trioderegion/steinhardts-support-desk#11]
**Describe the issue**
The icon for the attack Devour Life is missing on the character sheet of the Parasitic Geist.

**Observed locations**
Foundry VTT

**Expected corrections**
Adding/Fix Icon.

**Screenshot**
![9abce9dba06e669abfb15e023a653d9b](https://github.com/trioderegion/steinhardts-support-desk/assets/112840716/65cc3e5b-d566-4109-8510-8dffab785990)

**System Information (please complete the following information):**
Foundry V11.311 (Using Steinhardt module 1.0.8)

**Comment by trioderegion** [comment]
Confirmed missing. Thank you.
