### ISSUE TITLE
[Content] New content issue

### ISSUE THREAD

**Issue by nahtingyingyue** [trioderegion/steinhardts-support-desk#13]
**Not Received Foundry module Key**
A clear and concise description of what content error has been observed.

**Observed locations**
- It might be just I don't know where to find the Foundry key however I was expecting to get a foundry key on Sunday and I did not get it
- I got the Deluxe edition with the digital asset bundle 2

**Expected corrections**
- Either a direction to where I might find the foundry key or a new key

**Screenshots**

**Desktop (please complete the following information):**

**System Information (please complete the following information):**
 - Foundry Version [e.g. `v11`]
 - dnd5e System Version [e.g. `2.3.1`]

**Additional context**

**Comment by trioderegion** [comment]
Hi there, any updates on this? If you still haven't received your keys, I would suggest stopping by Monkey's discord at https://discord.gg/monkeydm and asking there.

This repo is primarily concerned with the operation/presentation of the FVTT module implementation :)
