### ISSUE TITLE
[Content] Explosive Bullet Price Inaccuracy

### ISSUE THREAD

**Issue by AraMoks** [trioderegion/steinhardts-support-desk#14]
**Describe the issue**
The price for Explosive Bullets is incorrect. Based on the information in the book, one Explosive Bullet should cost 4gp. However, the module displays their price as 30sp instead.

**Observed locations**
- 'Steinhardt's Items' -> 'Weapons' -> 'Firearms' -> 'Ammunition' -> 'Explosive Bullet'

**Comment by trioderegion** [comment]
The price for the next line's "Explosive Cannonballs" were used erroneously. Corrected, Thank you.
