### ISSUE TITLE
[Bug] Spells aren't scaling with higher level slots

### ISSUE THREAD

**Issue by Atrox-Primus** [trioderegion/steinhardts-support-desk#15]
**Describe the bug**
Per title. When upcast, Steinhardt spells are not increasing their damage. 

**Does this occur with all other modules disabled? If not, list minimum required module set to reproduce issue.**
 * Yes

**To Reproduce**
1. Put Bone Shield on character sheet with higher than first level spell slots. 
2. Use Bone Shield with a 2nd or higher level spell slot
3. See how it only rolls 1d12

**Expected behavior**
For each spell level above 1, it should roll an additional d12.

**Screenshots**
![xlr3ehki0akb1](https://github.com/trioderegion/steinhardts-support-desk/assets/147000488/26769e0e-22e3-41ff-9965-f8e1c10c888b)
![Elementaldrakes2-3e](https://github.com/trioderegion/steinhardts-support-desk/assets/147000488/b1686962-2ade-4fbe-b88b-37ec8d879840)

**System Information (please complete the following information):**
 - Foundry Version v11 Stable
 - dnd5e System Version 2.3.1

**Additional context**
Seems to affect more than just Bone Shield. Full List here, sorted by spell level, from lowest to highest

The only time scaling was implemented correctly was when the scaling was non-linear, such as Spectral Fury. I'm guessing whoever setup the spells thought the upcast scaling should happen automatically so long as they set it to increase by spell level? But at least on my foundry without other mods, it doesn't. 

Also of note is that Malicious Rancor is set up to scale, but scales incorrectly, applying it's increased damage to both the throw damage and to the detonation damage, when it should only be the detonation damage that increases.

1. Bone Claws (this is actually setup to increase, but only partially and in an unusual way, probably due to how weirdly it scales. Probably nothing can be done)
2. Bone Shield
3. Electrify
4. Fractured Shell
5. Phalangeal Shot
6. Spectral Slash
7. Arm Cannon
8. Blind Ambush
9. Bludgeoning Horror
10. Gravity Storm
11. Lightning Charged
12. Rupturing Curse
13. Skeletal Tail
14. Displacing Maw
15. Osseous Impalement
16. Fling
17. Jumping Jolt

**Comment by trioderegion** [comment]
Does this occur with all other modules disabled? Spell scaling with an empty field should use its defined damage formula.

**Comment by Atrox-Primus** [comment]
Certain. Here's a fresh pic sheet with the darkmode setting turned off. And proof of the lack of active modules. See that bone shield was cast at 5th level but didn't scale. This is a fresh world just for testing Steinhardt, no modules have ever been installed on it, aside from Steinhardt.

I agree that that's probably how it 'should' work, but it isn't working like that. At least not for me
It does work for cantrips with blank scaling (I tested those), but for whatever reason 'spell level' with blank scaling doesn't work.

> Does this occur with all other modules disabled? Spell scaling with an empty field should use its defined damage formula.
> 
> Edit: Sorry, I see that you indicated all other modules are disabled, but the sheet screenshot does not appear to be the core sheet. Are you certain all modules are disabled?

![Elementaldrakes2-3e](https://github.com/trioderegion/steinhardts-support-desk/assets/147000488/d874c5fc-4e10-4d43-9705-922dee8708c5)

**Comment by trioderegion** [comment]
Thanks for the feedback. This is unexpected behavior, possibly at the system level. I will dig into it.
