### ISSUE TITLE
[Mechanics] New Request - Add the possibility to hide/occult the art panel in Steinhardt's Note object type

### ISSUE THREAD

**Issue by juanmaperezortiz** [trioderegion/steinhardts-support-desk#19]
As an improvement to make journals for players using the theme of the setting but limiting the access of the information the DM give to them, I suggest to add an extra functionality in the art panel menu to hide the cards

As shown in the screenshot below, it would be adding an extra button within the object to hide the art panel

As an alternative, I propose to have another object that shares the same properties but does not include the art panel. The reason for this is I believe some DMs, including me, would want to benefit of the aesthetic of the journal but don't allow links that point to more information or show images, as it happens with the compendium

![image](https://github.com/trioderegion/steinhardts-support-desk/assets/116557363/e4071342-3509-488c-85f3-f60ec1ef0b79)

**Comment by trioderegion** [comment]
![image](https://github.com/trioderegion/steinhardts-support-desk/assets/14878515/bf56514c-9a2f-49c0-99e2-1253bcc8739e)
![image](https://github.com/trioderegion/steinhardts-support-desk/assets/14878515/a04e5b98-43c7-45c9-bbf9-98cfb20f12f3)

Closed in upcoming release.
