### ISSUE TITLE
[Content] Cannon is missing 'Ammunition' property

### ISSUE THREAD

**Issue by Drag0nF** [trioderegion/steinhardts-support-desk#20]
The Cannon item in the compendium (Steinhardts items->Weapons->Firearms) is missing the 'ammunition property, so it won't ask to be loaded with cannonballs- not a BIG issue- fixed it easily on my end, would just be best if it is set to ammunition already out of the box.

**Comment by trioderegion** [comment]
Corrected in upcoming update.
