### ISSUE TITLE
[Content] Suggestion- add a description and add 1d6 to the 'other formula' for the gatling gun variant of the Living Artillery

### ISSUE THREAD

**Issue by Drag0nF** [trioderegion/steinhardts-support-desk#23]
**Describe the issue**
Just a suggestion to improve the statblock- add the description for how the gatling gun works for the Living Artillery onto the item, rather than just the description explaining how it could alternatively have a gatling gun. Also, for the way the Gatling gun works, add a 1d6 to the other formula for the gatling gun variant, to allow for the mechanic it has to be simplified

**Observed locations**
 - 'Foes' -> 'Living Artillery'

**Comment by trioderegion** [comment]
Item description and other formula expanded for easier use.
