### ISSUE TITLE
Custom Made Trick Weapons unable to roll damage.

### ISSUE THREAD

**Issue by Sinblade723** [trioderegion/steinhardts-support-desk#30]
**Describe the bug**
When making and using a custom made trick weapon one is able to roll the attack but the main damage button display's the error message in a red box "undefined is not iterable (cannot read property Symbol (Symbol.iterator)) [Detected 1 package: system:dnd5e]

**Does this occur with all other modules disabled? If not, list minimum required module set to reproduce issue.**
 * Yes

**To Reproduce**
Create a custom trick weapon and click damage button after filling out the normal fields

**Expected behavior**
Being able to roll damage

**Screenshots**
![Steinhardt Custom Trick Weapon Bug](https://github.com/trioderegion/steinhardts-support-desk/assets/120570961/32b2a3cf-2325-4ccd-a6e5-d4442c9c9f3b)

**System Information (please complete the following information):**
 - Browser: Chrome
 - Foundry Version : Latest
 - dnd5e System Version [Latest]

**Additional context**

**Comment by trioderegion** [comment]
Fixed in 3.0.1
