### ISSUE TITLE
Street of Terror map 3

### ISSUE THREAD

**Issue by D3rp10101010101012** [trioderegion/steinhardts-support-desk#33]
There seems to be no scene for map 3 for the last fight within the church. 

**Expected corrections**
To get another map added to the scene pack with the correct tokens added for it. 

**Screenshots**
![map](https://github.com/trioderegion/steinhardts-support-desk/assets/162379090/d856a7cd-916e-42ba-ba80-972621a8547e)

**System Information (please complete the following information):**
 - Foundry Version [e.g. `v11`]
 - dnd5e System Version 3.0.1

**Additional context**

**Comment by trioderegion** [comment]
Resolved on user's end.
