### ISSUE TITLE
A few minor things

### ISSUE THREAD

**Issue by IAskedB4U** [trioderegion/steinhardts-support-desk#35]
The rifle is marked as a simple melee weapon and has a range of 150/500, and the "Dead Eye", "Ricochet", and "Riposte" invocations aren't put in as invocations.

 - 'Weapons' -> 'Rifle'
 - 'Subclasses' -> 'Warlock' -> 'Eldritch Invocations'

The rifle should be changed to a martial ranged weapon with a range of 120/240, and the "Dead Eye", "Ricochet", and "Riposte" invocations should be put in as invocations.

**Comment by trioderegion** [comment]
Thank you for the callouts and your patience. Corrected in upcoming version.
