### ISSUE TITLE
[Bug] fan fire not allowing attack rolls after opening character sheet

### ISSUE THREAD

**Issue by mr3spell** [trioderegion/steinhardts-support-desk#36]
**Describe the bug**
Fan fire not allowing attack rolls after opening a character sheet until an application reload

**Does this occur with all other modules disabled? If not, list minimum required module set to reproduce issue.**
 * Yes
 * (it says warpgate in the template so I tested it both with and without warp gate 1.19.2)

**To Reproduce**
1. create new world, enable SEGH
2. create a character, lvl 3 with a SGEH subclass. (I did jaeger with sanguine chapter, did not bother testing phb subclasses)
3. give character a pistol (tried both equipped and unequipped)
4. open character sheet (either legacy or d&d 3.0 sheet)
5. use pistol and select fan fire
6. try to click the fan fire attack button that appears in the chat

**Expected behavior**
Fan fire attack expected to roll attacking dice. 

**Screenshots**

**System Information (please complete the following information):**
 - Browser, foundry client, brave
 - Foundry Version 11 build 351
 - dnd5e System Version 3.1.1

**Additional context**
Normal pistol shot works fine. Under lvl 3 with a subclass works fine. Reloading the application allows click the fan fire attack button that appears in chat until a character sheet is opened up. Removing the sanguine chapter along with advancement changes allows rolling fan fire attack with no client reload. Quick test each jaeger subclass has the same problem. Same issue happened with a lvl 5 shadow rogue but not additional testing as been done.

**Comment by trioderegion** [comment]
Reproduced. Unsure if strictly related to having a subclass, but fixes are underway.
