### ISSUE TITLE
Missing foundry module

### ISSUE THREAD

**Issue by nahtingyingyue** [trioderegion/steinhardts-support-desk#39]
Hi 
I got the deluxe tier and the addon of the digital asset bundle. I remember signing to have the foundry module but I have not received a digital code. I have tried other version of support and have only received confirmation that you have got my email, but no response. That was a week ago. I was wondering if I could receive my code for the foundry module. If you need my email to check my order, it is joseph@jskw.co.uk.
Thank you

**Comment by trioderegion** [comment]
If this is still unresolved, please contact BackerKit support and they should be able to sort it out.

Best of luck.
