### ISSUE TITLE
[Bug] 'The Remedy' Journal pins don't open

### ISSUE THREAD

**Issue by dabriz1024** [trioderegion/steinhardts-support-desk#41]
**Describe the bug**
In 'The Remedy' adventure within the Steinhardt module for Foundry VTT, the note pins in the various scenes don't seem to work for me. In all the other adventures that have them, I can double click on them and see what the note is for that section of the map. However, for the maps on 'The Remedy', double clicking these notes does not create a pop up window with that information.

**Does this occur with all other modules disabled? If not, list minimum required module set to reproduce issue.**
 * Yes
 * 
**To Reproduce**
1. Open 'The Remedy' adventure on Foundry
2. Load any of the three scenes.
3. Try to open the pinned notes present on the scene noting the different areas.
4. See error, no pop-up window appears.

**Expected behavior**
A pop-up window with the note appears.

**Screenshots**
![image](https://github.com/user-attachments/assets/03816ee4-0a5a-4f1c-8ed9-59edf076de38)

**System Information (please complete the following information):**
 - Foundry Version v12.331
 - dnd5e System Version 3.3.1

**Additional context**
The notes still appear when going through the Journal tab, they're just not appearing via the pins specifically within 'The Remedy'

**Comment by trioderegion** [comment]
Links corrected and converted to Map Location types.
