### ISSUE TITLE
[Bug] ActiveEffect "dnd5eincapacitat" does not exist!

### ISSUE THREAD

**Issue by victorhsantiago** [trioderegion/steinhardts-support-desk#46]
**Describe the bug**
When leveling a Jeager to level 2 this error message appears `ActiveEffect "dnd5eincapacitat" does not exist!`

**Does this occur with all other modules disabled? If not, list minimum required module set to reproduce issue.**
No
 * `Dynamic effects using Active Effects` version `12.03`

**To Reproduce**
1. Create a Jaeger
2. Level it up to level 2
3. Complete leveling process 

**Expected behavior**
No error should appear

**Screenshots**
![image](https://github.com/user-attachments/assets/f76d1146-3639-455b-83e6-f38fa23a14c2)

**System Information (please complete the following information):**
 - Foundry Version `v12`
 - dnd5e System Version `4.1.1`

**Additional context**
I'm not sure what the effects of this possible bug are :)

**Comment by trioderegion** [comment]
I dont think I can do anything about other modules breaking. MIDI and DAE are not supported in 4.x yet, if I remember correctly.

Just to be sure, without MIDI/DAE, this error does not appear?

**Comment by trioderegion** [comment]
https://gitlab.com/tposney/dae/-/issues/456

Crossposted issue. Will close here when its confirmed proper operation occurs without DAE/MIDI enabled.

**Comment by victorhsantiago** [comment]
> Just to be sure, without MIDI/DAE, this error does not appear?

Sorry for the late response. Yes, that's correct, no errors when there are no other module enabled.

Thanks for the crosspost, by the way :)

**Comment by trioderegion** [comment]
Keeping open as 'wontfix' for followups/monitoring.

**Comment by trioderegion** [comment]
@victorhsantiago It appears that the bug has been addressed in DAE, could you confirm and comment on the linked issue?

**Comment by victorhsantiago** [comment]
I've just tested the new DAE version, and the error is gone. Thank you for your help!
