### ISSUE TITLE
[Content] Rifles don't have artillery property.

### ISSUE THREAD

**Issue by Atrox-Primus** [trioderegion/steinhardts-support-desk#8]
**Describe the issue**
Rifle doesn't have the artillery property, and therefore runs off Dexterity.

**Observed locations**
Where this content issue occurs.
- Steinhardt's Guide -> Weapons -> Firearms -> Rifle

**Expected corrections**
Click the artillery checkbox.

**Screenshots**
![xlr3ehki0akb1](https://github.com/trioderegion/steinhardts-support-desk/assets/147000488/5a19e47d-7967-433b-910d-ed2c493486d5)

**Desktop (please complete the following information):**
Windows...? 

**System Information (please complete the following information):**
Foundry V11 Stable

**Additional context**
May also not be applied to any rifle trick weapon parts, haven't checked.

**Comment by trioderegion** [comment]
Rifles having this property is an error in the source material and should NOT have the artillery property, but rather "Barrel 2, Reload (S)" as configured in the compendium.

Thanks for the keen eye regardless!
