### ISSUE TITLE
[Mechanics] A [Take Damage] Button for the Serpent/Python Bladewhips

### ISSUE THREAD

**Issue by Atrox-Primus** [trioderegion/steinhardts-support-desk#9]
**Is your feature request related to a problem? If so, please describe.**
Play finds it frustrating to both remember to deduct 1 hit point at the start his turns when he has the transformed version of the Serpent  Bladewhip and frustrating to deduct that health by clicking the versatile damage button and then by right click and then applying that damage to his token.

**Describe the solution you'd like**
I'd like a button on the weapon's chat card, similar to the 'attack', 'damage' or 'versatile' buttons that, when pressed, reduces the weapon wielder's health by 1, or rather inflicts 1 point of piercing damage on the wielder.

**Describe alternatives you've considered**
What I did just a day before the Steinhardt module came out was create a feature that had no purpose other than to consume '1' of the 'attributes.hp.value' attribute. If the above solution can't be done, maybe a "Rapier Form Bleed" macro can be added to the trick weapon's components? So that all may at least have that sort of macro when they transform the weapon?

**Additional context**
Any change that is made will need to be done to both the Serpent's Bladewhip and the Python Bladewhip, which is the upgraded form with the same drawback.

**Comment by trioderegion** [comment]
While I cannot preconfigure the item to consume the HP resource (Needs to be attached to an actor), I have added a "Serpent Drain" item to the transformed states of both weapons following the alternative approach presented.

As the system stands, this is about as close as I can practically get to automatic damage application.
